name: Build PC App
on:
  push:

defaults:
  run:
    working-directory: pc-app

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create virtual environment
        run: python -m venv .venv

      - name: Activate virtual environment
        run: .\.venv\Scripts\activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run PyInstaller
        run: pyinstaller --onefile --name alexa-ifttt-pc-notification.exe app.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: bundled-exe
          path: pc-app/dist/alexa-ifttt-pc-notification.exe
